[package]
name = "RustServer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.5"
hyper = "1.4.1"
serde_json = "1.0.127"
tower = "0.5.0"